### ISSUE TITLE
Do not work for some zones which have a alias.

### ISSUE THREAD

**Issue by remmmmi** [herr-fridolin/FridosSmartPing#2]
Example: R8D2
![2024-06-26 205807](https://github.com/herr-fridolin/FridosSmartPing/assets/43727126/748ff88f-dc9e-4137-9b47-fc59e1167833)

BTW: The welcome strings looks weird in some languages. (Chinese, Japanese, Korean)
![2024-06-26 210044](https://github.com/herr-fridolin/FridosSmartPing/assets/43727126/7cb1540b-2f95-427b-83ba-4c03913de42e)

**Comment by herr-fridolin** [comment]
Hey,

thanks a lot, these are some oversights.
We will test with Rundown 8 and other languages asap.

**Comment by herr-fridolin** [comment]
Updated the mod to 1.2.5.

**Comment by herr-fridolin** [comment]
Both issues should be resolved, please let me know if that is not the case :)
